// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Z8V32MYhnBRQSzMFWObnvHOLSiqzoaU',
    appId: '1:593493225506:web:8ac46724fbb1a562bbda7b',
    messagingSenderId: '593493225506',
    projectId: 'travelexpense-12035',
    authDomain: 'travelexpense-12035.firebaseapp.com',
    storageBucket: 'travelexpense-12035.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXcegPAnlFT3eG4LjAQRUzfvNgqjWGYFQ',
    appId: '1:593493225506:android:597ba75bf264a03ebbda7b',
    messagingSenderId: '593493225506',
    projectId: 'travelexpense-12035',
    storageBucket: 'travelexpense-12035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXv9m9Ufq-DkXkTbVkkdlqyHdK6pju5_Q',
    appId: '1:593493225506:ios:b453366897a84081bbda7b',
    messagingSenderId: '593493225506',
    projectId: 'travelexpense-12035',
    storageBucket: 'travelexpense-12035.appspot.com',
    iosBundleId: 'com.example.fcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXv9m9Ufq-DkXkTbVkkdlqyHdK6pju5_Q',
    appId: '1:593493225506:ios:b453366897a84081bbda7b',
    messagingSenderId: '593493225506',
    projectId: 'travelexpense-12035',
    storageBucket: 'travelexpense-12035.appspot.com',
    iosBundleId: 'com.example.fcc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Z8V32MYhnBRQSzMFWObnvHOLSiqzoaU',
    appId: '1:593493225506:web:66865f16973108ddbbda7b',
    messagingSenderId: '593493225506',
    projectId: 'travelexpense-12035',
    authDomain: 'travelexpense-12035.firebaseapp.com',
    storageBucket: 'travelexpense-12035.appspot.com',
  );

}